version: "3.9"

services:
  app:
    platform: linux/amd64
    environment:
      TZ: "${TZ:-UTC}"
      PORT: "${PORT:-3000}"
      DATABASE_HOST: "${DATABASE_HOST:-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-template}"
    depends_on:
      - postgres

  postgres:
    image: postgres:17-bookworm
    env_file:
      - path: ./.env
        required: false
    environment:
      TZ: "${TZ:-UTC}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-template}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
    command: >
      postgres
      -c "port=${POSTGRES_PORT:-5432}"
      -c "log_destination=stderr"
